# Generated by Django 5.0.3 on 2024-03-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating_revolution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
