# Generated by Django 5.1 on 2024-08-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_revolution', '0002_alter_company_options_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
