# Generated by Django 5.1 on 2024-08-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating_revolution', '0005_remove_company_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyphotos',
            old_name='photo',
            new_name='url',
        ),
    ]
