version: '3.8'

services:
  rating_revolution_api:
    build: .
    container_name: rating_revolution_api
    restart: always
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DOMAIN_BACKEND=${DOMAIN_BACKEND}
      - FRONTEND_HOST=${FRONTEND_HOST}
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    networks:
      - rating_revolution_api_network

#  nginx_rating_revolution_api:
#    image: nginx:latest
#    container_name: nginx_rating_revolution_api
#    restart: always
#    volumes:
#      - ./nginx:/etc/nginx
#    ports:
#      - "8080:80"
#    depends_on:
#      - rating_revolution_api
#    networks:
#      - rating_revolution_api_network

networks:
  rating_revolution_api_network:
    driver: bridge